### ISSUE TITLE
captureVideoFrame is not a function. 

### ISSUE THREAD

**Issue by sachinshah114** [ilkkao/capture-video-frame#4]
As I have seen in demo, I have set capture-video-frame.js file in my assets/js/capture-video-frame.js folder and I have load that js from index.js file. In browser I have check that js is load or not. And It's load fine. 

I'm using your code in angular 4. And I got error like this. 

ERROR TypeError: this.captureVideoFrame is not a function

When I remove this keyword from capturteVideoFrame , then it shows error with red underline. 

The error message is this. -> Cannot find name 'captureVideoFrame'.

**Comment by ilkkao** [comment]
If you use angular and build system you probably want to do it like this:

```
import captureVideoFrame from 'capture-video-frame';

const { blob, dataUri } = captureVideoFrame.captureVideoFrame(video, 'jpeg');
```

**Comment by sachinshah114** [comment]
I'm closing this issue. Actually I have use other option. Thanks for the reply.
